library(dplyr)
library(shiny)
library(DT)
library(shinyjs)
library(ggplot2)

playerxgoals <- readRDS('IgnoreList/xGoalsByPlayer.rds')
teamxgoals <- readRDS('IgnoreList/xGoalsByTeam.rds')
xgbygame <- readRDS('IgnoreList/xGoalsByTeam_byGame.rds')
keeperxgoals <- readRDS('IgnoreList/xGoalsByKeeper.rds')
conferences <- read.csv('teamsbyconferencebyseason.csv')

source('ShooterxGoalsFunction.R')
source('TeamxGoalsFunction.R')
source('KeeperxGoalsFunction.R')
