
# This is the user-interface definition of a Shiny web application.
# You can find out more about building applications with Shiny here:
#
# http://shiny.rstudio.com
#

library(shiny)

shinyUI(
  navbarPage(title = HTML('<b>ASA Database</b>'),
             theme = 'bootstrap_edited.css',
             navbarMenu(strong('xGoals'),
                        # Players totals tab panel ####
                        tabPanel('Players: totals',
                                 sidebarLayout(
                                   sidebarPanel(width = 2,
                                                actionButton('shooting_action',
                                                             label = 'Apply filters'),
                                                numericInput('shooting_minshots',
                                                             "Minimum shots:",
                                                             value = 0,
                                                             min = 0, max = 100, step = 10),
                                                numericInput('shooting_minkeypasses',
                                                             'Minimum key passes:',
                                                             value = 0,
                                                             min = 0, max = 100, step = 10),
                                                radioButtons('shooting_seasonordate',
                                                             'Filter by:',
                                                             choices = c('Season', 'Date')),
                                                conditionalPanel(condition = "input.shooting_seasonordate == 'Season'",
                                                                 checkboxGroupInput('shooting_seasonfilter',
                                                                                    'Select seasons:',
                                                                                    choices = min(playerxgoals$Season):max(playerxgoals$Season),
                                                                                    selected = max(playerxgoals$Season))),
                                                conditionalPanel(condition = "input.shooting_seasonordate == 'Date'",
                                                                 dateInput('shooting_date1',
                                                                           'From:',
                                                                           value = min(playerxgoals$date[playerxgoals$Season == max(playerxgoals$Season)]),
                                                                           min = min(playerxgoals$date),
                                                                           max = max(playerxgoals$date),
                                                                           format = 'mm/dd/yyyy'),
                                                                 dateInput('shooting_date2',
                                                                           'To:',
                                                                           value = max(playerxgoals$date),
                                                                           min = min(playerxgoals$date),
                                                                           max = max(playerxgoals$date),
                                                                           format = 'mm/dd/yyyy')
                                                ),                  
                                                h5(HTML('<b>Other filters:</b>')),
                                                checkboxInput('shooting_byteams',
                                                              label = 'Split players by teams',
                                                              value = F),
                                                checkboxInput('shooting_byseasons',
                                                              label = 'Split players by seasons',
                                                              value = T),
                                                checkboxInput('shooting_other',
                                                              label = 'Include non PK/FK',
                                                              value = T),
                                                checkboxInput('shooting_pk',
                                                              label = 'Include PKs',
                                                              value = T),
                                                checkboxInput('shooting_fk',
                                                              label = 'Include FKs',
                                                              value = T)),
                                   
                                   mainPanel(
                                     # div(style="display: inline-block;vertical-align:bottom; width: 250px;", h1('Player xGoals')),
                                     # div(style="display: inline-block;vertical-align:bottom; width: 250px;", downloadButton('player_download', 'Download CSV')),
                                     h1('Player xGoals'),
                                     p(paste0('Updated through games on ', max(as.Date(playerxgoals$date)))),
                                     downloadButton('player_download', 'Download CSV'),
                                     br(),
                                     tabsetPanel(id = 'player_subtab',
                                                 tabPanel('Totals',
                                                          DT::dataTableOutput('shootertable')
                                                 ),
                                                 tabPanel('Scatter plots',
                                                          fluidPage(fluidRow(
                                                            column(3,
                                                                   selectInput('shooterplot_xvar',
                                                                               label = 'X-axis variable',
                                                                               choices = sort(c('xG', 'xA', 'xG/Shot' = 'xGperShot', 
                                                                                                'xA/Pass' = 'xAperPass', 'Shots on target' = 'OnTarget',
                                                                                                'Shots', 'Key passes' = 'KeyP', 'Goals', 'G-xG/Shot' = 'GmxGperShot',
                                                                                                'Assists' = 'Assts', 'G-xG', 'A-xA', 'xPlacement' = 'xPlace')),
                                                                               selected ='xG')),
                                                            column(3,
                                                                   selectInput('shooterplot_yvar',
                                                                               label = 'Y-axis variable',
                                                                               choices = sort(c('xG', 'xA', 'xG/Shot' = 'xGperShot', 
                                                                                                'xA/Pass' = 'xAperPass', 'Shots on target' = 'OnTarget',
                                                                                                'Shots', 'Key passes' = 'KeyP', 'Goals', 'G-xG/Shot' = 'GmxGperShot',
                                                                                                'Assists' = 'Assts', 'G-xG', 'A-xA', 'xPlacement' = 'xPlace')),
                                                                               selected ='xG/Shot')),
                                                            plotOutput('shooterplot'))))
                                     )))),
                        # Players per 96 tab ####
                        tabPanel('Players: per 96',
                                 sidebarLayout(
                                   sidebarPanel(width = 2,
                                                actionButton('shooting_per96_action',
                                                             label = 'Apply filters'),
                                                numericInput('shooting_per96_minfilter',
                                                             label = 'Minimum minutes:',
                                                             value = 0,
                                                             min = 0, max = 3000, step = 250),
                                                numericInput('shooting_per96_minshots',
                                                             "Minimum shots:",
                                                             value = 0,
                                                             min = 0, max = 100, step = 10),
                                                numericInput('shooting_per96_minkeypasses',
                                                             'Minimum key passes:',
                                                             value = 0,
                                                             min = 0, max = 100, step = 10),
                                                radioButtons('shooting_per96_seasonordate',
                                                             'Filter by:',
                                                             choices = c('Season', 'Date')),
                                                conditionalPanel(condition = "input.shooting_per96_seasonordate == 'Season'",
                                                                 checkboxGroupInput('shooting_per96_seasonfilter',
                                                                                    'Select seasons:',
                                                                                    choices = 2015:max(playerxgoals$Season), # No minutes before 2015 yet
                                                                                    selected = max(playerxgoals$Season))),
                                                conditionalPanel(condition = "input.shooting_per96_seasonordate == 'Date'",
                                                                 dateInput('shooting_per96_date1',
                                                                           'From:',
                                                                           value = min(playerxgoals$date[playerxgoals$Season == max(playerxgoals$Season)]),
                                                                           min = min(playerxgoals$date[playerxgoals$Season > 2014]),
                                                                           max = max(playerxgoals$date[playerxgoals$Season > 2014]), # No minutes before 2015 yet
                                                                           format = 'mm/dd/yyyy'),
                                                                 dateInput('shooting_per96_date2',
                                                                           'To:',
                                                                           value = max(playerxgoals$date),
                                                                           min = min(playerxgoals$date[playerxgoals$Season > 2014]),
                                                                           max = max(playerxgoals$date[playerxgoals$Season > 2014]),
                                                                           format = 'mm/dd/yyyy')
                                                ),                  
                                                # We don't have teams in the per-minute data yet
                                                # checkboxInput('shooting_per96_byteams',
                                                #               label = 'Split players by teams',
                                                #               value = F),
                                                checkboxInput('shooting_per96_byseasons',
                                                              label = 'Split players by seasons',
                                                              value = T),
                                                checkboxInput('shooting_per96_other',
                                                              label = 'Include non PK/FK',
                                                              value = T),
                                                checkboxInput('shooting_per96_pk',
                                                              label = 'Include PKs',
                                                              value = T),
                                                checkboxInput('shooting_per96_fk',
                                                              label = 'Include FKs',
                                                              value = T)),
                                   
                                   mainPanel(
                                     # div(style="display: inline-block;vertical-align:bottom; width: 250px;", h1('Player xGoals')),
                                     # div(style="display: inline-block;vertical-align:bottom; width: 250px;", downloadButton('player_download', 'Download CSV')),
                                     h1('Player xGoals: per 96 minutes'),
                                     p(paste0('Updated through games on ', max(as.Date(playerxgoals$date)))),
                                     downloadButton('player_per96_download', 'Download CSV'),
                                     br(),
                                     tabsetPanel(id = 'player_per96_subtab',
                                                 tabPanel('Tables',
                                                          DT::dataTableOutput('shootertable_per96')
                                                 ),
                                                 tabPanel('Scatter plots',
                                                          fluidPage(fluidRow(
                                                            column(3,
                                                                   selectInput('shooterplot_per96_xvar',
                                                                               label = 'X-axis variable',
                                                                               choices = sort(c('xG', 'xA', 'Minutes' = 'Min',
                                                                                                'Shots on target' = 'SoT',
                                                                                                'Shots', 'Key passes' = 'KeyP', 'Goals', 
                                                                                                'Assists' = 'Assts', 'G-xG', 'A-xA', 
                                                                                                'xG+xA', 'xPlacement' = 'xPlace')),
                                                                               selected ='Min')),
                                                            column(3,
                                                                   selectInput('shooterplot_per96_yvar',
                                                                               label = 'Y-axis variable',
                                                                               choices = sort(c('xG', 'xA', 'xG/Shot' = 'xGperShot', 
                                                                                                'xA/Pass' = 'xAperPass', 'Shots on target' = 'OnTarget',
                                                                                                'Shots', 'Key passes' = 'KeyP', 'Goals', 
                                                                                                'Assists' = 'Assts', 'G-xG', 'A-xA', 'xPlacement' = 'xPlace')),
                                                                               selected ='G-xG')),
                                                           
                                                            plotOutput('shooterplot_per96'))))
                                     )))),
                        # Team tab panel ####
                        tabPanel('Teams',
                                 sidebarLayout(
                                   sidebarPanel(width = 2,
                                                radioButtons('team_advanced',
                                                             '',
                                                             choices = c('Basic stats', 'Advanced stats')),
                                                radioButtons('team_seasonordate',
                                                             'Filter by:',
                                                             choices = c('Season', 'Date')),
                                                conditionalPanel(condition = "input.team_seasonordate == 'Season'",
                                                                 checkboxGroupInput('team_seasonfilter',
                                                                                    'Select seasons:',
                                                                                    choices = min(teamxgoals$Season):max(teamxgoals$Season),
                                                                                    selected = max(teamxgoals$Season))),
                                                conditionalPanel(condition = "input.team_seasonordate == 'Date'",
                                                                 dateInput('team_date1',
                                                                           'From:',
                                                                           value = min(teamxgoals$date[teamxgoals$Season == max(teamxgoals$Season)]),
                                                                           min = min(teamxgoals$date),
                                                                           max = max(teamxgoals$date),
                                                                           format = 'mm/dd/yyyy'),
                                                                 dateInput('team_date2',
                                                                           'To:',
                                                                           value = max(teamxgoals$date),
                                                                           min = min(teamxgoals$date),
                                                                           max = max(teamxgoals$date),
                                                                           format = 'mm/dd/yyyy')
                                                ),
                                                checkboxInput('team_byseasons',
                                                              label = 'Split teams by seasons',
                                                              value = T),
                                                selectInput('team_pattern',
                                                            'Pattern of play:',
                                                            choices = c('All', sort(unique(teamxgoals$patternOfPlay.model))),
                                                            selected = 'All'),
                                                checkboxInput('team_evenstate',
                                                              label = 'Even gamesate only',
                                                              value = F),
                                                checkboxGroupInput('team_home',
                                                                   label = 'Venue:',
                                                                   choices = c('Home', 'Away'),
                                                                   selected = c('Home', 'Away'))),
                                   mainPanel(
                                     h1('Team shots data'),
                                     p(paste0('Updated through games on ', max(as.Date(teamxgoals$date)))),
                                     tabsetPanel(id = 'team_subtab',
                                                 tabPanel('Totals',
                                                          downloadButton('team_download', 'Download CSV'),
                                                          br(),
                                                          br(),
                                                          div(id = 'west', conditionalPanel(condition = "input.team_seasonordate == 'Season' && input.team_seasonfilter.length == 1",
                                                                                            h2('Western conference')),
                                                              DT::dataTableOutput('teamtotalxgoalswest')),
                                                          br(),
                                                          div(id = 'east', conditionalPanel(condition = "input.team_seasonordate == 'Season' && input.team_seasonfilter.length == 1",
                                                                                            h2('Eastern conference'),
                                                                                            DT::dataTableOutput('teamtotalxgoalseast')))
                                                 ),
                                                 tabPanel('Per game',
                                                          downloadButton('team_download_pergame', 'Download CSV'),
                                                          br(),
                                                          br(),
                                                          conditionalPanel(condition = "input.team_seasonordate == 'Season' && input.team_seasonfilter.length == 1",
                                                                           h2('Western conference')),
                                                          div(DT::dataTableOutput('teampergamexgoalswest')),
                                                          br(),
                                                          conditionalPanel(condition = "input.team_seasonordate == 'Season' && input.team_seasonfilter.length == 1",
                                                                           h2('Eastern conference'),
                                                                           div(DT::dataTableOutput('teampergamexgoalseast')))
                                                 ),
                                                 tabPanel('Scatter plots',
                                                          p(div(HTML("<i> All statistics on a per game basis. Not all teams labeled. </i>"))),
                                                          actionButton('team_action', 
                                                                       label = 'Apply filters'),
                                                          fluidPage(fluidRow(
                                                            column(4,
                                                                   selectInput('teamplot_xvar',
                                                                               label = 'X-axis variable',
                                                                               choices = c('Shots for' = 'ShtF', 'Shots against' = 'ShtA',
                                                                                           'Unassisted % for' = 'Solo%F',
                                                                                           'Unassisted % against' = 'Solo%A',
                                                                                           'Cross % for' = 'CrossPctF', 'Cross % against' = 'CrossPctA',
                                                                                           'Shots on target for' = 'OnTargetF', 'Shots on target against' = 'OnTargetA',
                                                                                           'GF', 'GA', 'GD', 'xGF', 'xGA', 'xGD', 'TSR', 'PDO', 'Points' = 'Pts'),
                                                                               selected = 'xGF')),
                                                            column(4,
                                                                   selectInput('teamplot_yvar',
                                                                               label = 'Y-axis variable',
                                                                               choices = c('Shots for' = 'ShtF', 'Shots against' = 'ShtA',
                                                                                           'Unassisted % for' = 'Solo%F',
                                                                                           'Unassisted % against' = 'Solo%A',
                                                                                           'Cross % for' = 'CrossPctF', 'Cross % against' = 'CrossPctA',
                                                                                           'Shots on target for' = 'OnTargetF', 'Shots on target against' = 'OnTargetA',
                                                                                           'GF', 'GA', 'GD', 'xGF', 'xGA', 'xGD', 'TSR', 'PDO', 'Points' = 'Pts'),
                                                                               selected = 'xGA')),
                                                            plotOutput('teamplot')))
                                                 )
                                     )
                                   )
                                 )
                        ),
                        tabPanel('Game-by-game xG',
                                 sidebarLayout(
                                   sidebarPanel(width = 2,
                                                radioButtons('teambygame_seasonordate',
                                                             'Filter by:',
                                                             choices = c('Season', 'Date')),
                                                conditionalPanel(condition = "input.teambygame_seasonordate == 'Season'",
                                                                 checkboxGroupInput('teambygame_seasonfilter',
                                                                                    'Select seasons:',
                                                                                    choices = min(xgbygame$Season):max(xgbygame$Season),
                                                                                    selected = max(xgbygame$Season))),
                                                conditionalPanel(condition = "input.teambygame_seasonordate == 'Date'",
                                                                 dateInput('teambygame_date1',
                                                                           'From:',
                                                                           value = min(xgbygame$Date[xgbygame$Season == max(xgbygame$Season)]),
                                                                           min = min(xgbygame$Date),
                                                                           max = max(xgbygame$Date),
                                                                           format = 'mm/dd/yyyy'),
                                                                 dateInput('teambygame_date2',
                                                                           'To:',
                                                                           value = max(xgbygame$Date),
                                                                           min = min(xgbygame$Date),
                                                                           max = max(xgbygame$Date),
                                                                           format = 'mm/dd/yyyy'))
                                   ),
                                   mainPanel(
                                     h1('Team xGoals by game'),
                                     p(paste0('Updated through games on ', max(as.Date(xgbygame$Date)))),
                                     downloadButton('teambygame_download', 'Download CSV'),
                                     br(),
                                     br(),
                                     DT::dataTableOutput('teamxgoalsbygame')
                                   )
                                 )
                        ),
                        # Keepers tab panel ####
                        tabPanel('Keepers',
                                 sidebarLayout(
                                   sidebarPanel(width = 2,
                                                actionButton('keeper_action',
                                                             label = 'Apply filters'),
                                                numericInput('keeper_minshots',
                                                             "Minimum shots faced:",
                                                             value = 0,
                                                             min = 0, max = 100, step = 10),
                                                radioButtons('keeper_seasonordate',
                                                             'Filter by:',
                                                             choices = c('Season', 'Date')),
                                                conditionalPanel(condition = "input.keeper_seasonordate == 'Season'",
                                                                 checkboxGroupInput('keeper_seasonfilter',
                                                                                    'Select seasons:',
                                                                                    choices = min(playerxgoals$Season):max(playerxgoals$Season),
                                                                                    selected = max(playerxgoals$Season))),
                                                conditionalPanel(condition = "input.keeper_seasonordate == 'Date'",
                                                                 dateInput('keeper_date1',
                                                                           'From:',
                                                                           value = min(playerxgoals$date[playerxgoals$Season == max(playerxgoals$Season)]),
                                                                           min = min(playerxgoals$date),
                                                                           max = max(playerxgoals$date),
                                                                           format = 'mm/dd/yyyy'),
                                                                 dateInput('keeper_date2',
                                                                           'To:',
                                                                           value = max(playerxgoals$date),
                                                                           min = min(playerxgoals$date),
                                                                           max = max(playerxgoals$date),
                                                                           format = 'mm/dd/yyyy')
                                                ),                  
                                                h5(HTML('<b>Other filters:</b>')),
                                                checkboxInput('keeper_byteams',
                                                              label = 'Split by teams',
                                                              value = F),
                                                checkboxInput('keeper_byseasons',
                                                              label = 'Split by seasons',
                                                              value = T),
                                                checkboxInput('keeper_othershots',
                                                              label = 'Include non PK/FK',
                                                              value = T),
                                                checkboxInput('keeper_pk',
                                                              label = 'Include PKs',
                                                              value = T),
                                                checkboxInput('keeper_fk',
                                                              label = 'Include FKs',
                                                              value = T)),
                                   
                                   mainPanel(
                                     tabsetPanel(
                                       tabPanel('Tables',
                                                h1('Keeper xGoals'),
                                                p(paste0('Updated through games on ', max(as.Date(keeperxgoals$date)))),
                                                downloadButton('keeper_download', 'Download CSV'),
                                                br(),
                                                br(),
                                                DT::dataTableOutput('keepertable')),
                                       tabPanel('Scatter plots',
                                                fluidPage(fluidRow(
                                                  column(4,
                                                         selectInput('keeperplot_xvar',
                                                                     label = 'X-axis variable',
                                                                     choices = c('Shots faced' = 'Shots', 'Goals allowed' = 'GA',
                                                                                 'GA/shot' = 'GAperShot', 'xG/Shot' = 'xGperShot',
                                                                                 'G-xG/shot' = 'GmxGperShot',
                                                                                 '%Shots headed' = 'Header%', 'Avg. distance' = 'Dist',
                                                                                 'xG faced' = 'xG', 'GA above average' = 'G-xG'),
                                                                     selected = 'xG')),
                                                  column(4,
                                                         selectInput('keeperplot_yvar',
                                                                     label = 'Y-axis variable',
                                                                     choices = c('Shots faced' = 'Shots', 'Goals allowed' = 'GA',
                                                                                 'GA/shot' = 'GAperShot', 'xG/Shot' = 'xGperShot',
                                                                                 'G-xG/shot' = 'GmxGperShot',
                                                                                 '%Shots headed' = 'Header%', 'Avg. distance' = 'Dist',
                                                                                 'xG faced' = 'xG', 'GA above average' = 'G-xG'),
                                                                     selected = 'G-xG')),
                                                  plotOutput('keeperplot')))
                                       )
                                     )
                                   ))
                        )
             ),
             # Glossary ####
             tabPanel(strong('Glossary'),
                      h1('Glossary'),
                      dataTableOutput('glossary')                        
             ),
             # App info ####
             tabPanel(strong('App info'),
                      h1('App info'),
                      p("We built this interactive web application to give ASA's loyal readers more control over 
                        sorting and filtering our data. We plan to grow this application out to include
                        more content, as well as more ways to view the content (like plots and other visuals, for example).
                        If you have an idea for a feature that will make the app totes better,
                        then please don't hesitate to email Matthias (mkullowatz at gmail) with your idea."),
                      br(),
                      p('We have been asked why we measure individual stats on a per-96-minute basis, rather than
                        per 90 minutes. No, we are not trying to be hip for the sake of being hip. The average MLS game
                        is 96 minutes long, including average stoppage times for each half, and thus our team per-game
                        statistics are actually per-96-minute statistics. To maintain internal consistency of our data,
                        we show player statistics on a per-96-minute basis, too, so that the average number of goals per game
                        at the team level will be equal to the average number of goals per 96 minutes at the player level.'),
                      br(),
                      p('Please note that the statistics displayed in this app are very similiar to, but not exactly
                        the same as, those in our static tables. This is because this app utilizes
                        updated xGoal models, fit through 2016, with a better method of capturing penalty kicks. For most
                        players the differences are negligible.'))
             
  )
)
